name: ğŸ“¦ï¸ Distribute Modules

on:
  push:
    branches: ["master"]

permissions:
  contents: write

jobs:
  metadata:
    name: âš™ï¸ Generate metadata
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.generate.outputs.release_tag }}
      release_name: ${{ steps.generate.outputs.release_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2
      - uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      - run: pdm install
      - name: Generate metadata
        id: generate
        run: pdm run meta update
  release:
    needs: metadata
    name: ğŸ”– Create release
    runs-on: ubuntu-latest
    if: ${{ needs.metadata.outputs.release_tag != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2
      - run: pdm install
      - name: Build release files
        run: pdm run modules release
      - uses: softprops/action-gh-release@v2
        with:
          name: ${{ needs.metadata.outputs.release_tag }}
          tag_name: ${{ needs.metadata.outputs.release_name }}
          make_latest: true
          files: release/*.zip
