name: ğŸ“‹ Review Modules

on:
  push:
    branches: ["master"]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: ğŸ” Check modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - name: Check modules
        run: |
          pdm install
          pdm run modules check
  test:
    name: ğŸ§ª Test modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Test modules
        run: |
          pdm install
          pdm run modules test
