name: ğŸ“‹ Review Modules

on:
  push:
    branches: ["master"]
    paths: ["modules/**"]
  pull_request:
    paths: ["modules/**"]
  workflow_dispatch:

jobs:
  check:
    name: ğŸ” Check files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - name: Check headers and metadata
        run: |
          pdm install
          pdm run check-headers
          pdm run check-metadata
  test:
    name: ğŸ§ª Test modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run packtest
        run: |
          pdm install
          pdm run test
